# Spring
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 47.98.35.95:8848
        namespace: 842a9626-6dea-4168-b1fd-4ccf9ad3a69c
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dictionary?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: root
  redis:
    host: 10.100.50.141
    port: 7001
    password:
    timeout: 5000
    database: 0

wj:
  auth:
    ignoreUrls: # 以下接口可以不走网关直接通过服务访问
      - /dictionary/ignore/**